import { Produit } from "../Models/produit";

export const PRODUITS: Produit[] = [
  { 
    id: 1, 
    codeFournisseur: 'BBI',
    codeProduit: 'BBI-VET-001', 
    nom: 'Body bébé coton', 
    prix: { '6-9 mois': 9.99 }, 
    devise: 'USD',
    region: 'Goma',
    classement: 'Vêtements & Mode',
    categorie: 'Vêtement',
    quantiteTotal: { 'rose': 45, 'bleu': 30 },
    type: 'Body',
    taille: ['6-9 mois'],
    couleur: ['rose', 'bleu'],
    description: 'Body confortable 100% coton pour bébé.', 
    imagesParCouleur: {
      'rose':'/assets/imagesProduits/bbi-vet-001/rose.jpeg',
      'bleu':'/assets/imagesProduits/bbi-vet-001/bleu.jpeg',
    },
    dateAjout: new Date('2024-01-10T10:00:00'),
    dateModification: new Date('2024-02-15T14:30:00')
  },
  { 
    id: 2, 
    codeFournisseur: 'BBI',
    codeProduit: 'BBI-VET-002', 
    nom: 'Pyjama bébé', 
    prix: { '12-18 mois': 12.99 }, 
    devise: 'USD',
    region: 'Beni',
    classement: 'Vêtements & Mode',
    categorie: 'Vêtement',
    quantiteTotal: { 'glauque': 12, 'chocolat': 25 },
    type: 'Pyjama',
    taille: ['12-18 mois'],
    couleur: ['glauque', 'chocolat'],
    description: 'Pyjama doux et chaud en velours.', 
    imagesParCouleur: {
      'glauque': '/assets/imagesProduits/bbi-vet-002/glauque.jpeg',
      'chocolat': '/assets/imagesProduits/bbi-vet-002/chocolat.jpeg'
    },
    dateAjout: new Date('2024-01-12T09:15:00'),
    dateModification: new Date('2024-01-12T09:15:00')
  },
  { 
    id: 3, 
    codeFournisseur: 'ACC-DIST',
    codeProduit: 'BBI-ACC-003', 
    nom: 'Chaussettes', 
    prix: { 'Taille unique': 2000 }, 
    devise: 'CDF',
    region: 'Butembo',
    classement: 'Vêtements & Mode',
    categorie: 'Accessoire',
    quantiteTotal: { 'rose': 50, 'multicolore': 40, 'bleu': 30, 'blanc': 100 },
    type: 'Chaussette',
    taille: ['Taille unique'],
    couleur: ['rose','multicolore', 'bleu', 'blanc'],
    description: 'Lot de 5 paires de chaussettes en coton.', 
    imagesParCouleur: {
      'rose' : '/assets/imagesProduits/bbi-acc-003/rose.jpeg',
      'multicolore' : '/assets/imagesProduits/bbi-acc-003/multicolore.png',
      'bleu' : '/assets/imagesProduits/bbi-acc-003/bleu.jpeg',
      'blanc' : '/assets/imagesProduits/bbi-acc-003/blanc.jpeg'
    },
    dateAjout: new Date('2023-12-20T16:45:00'),
    dateModification: new Date('2024-03-01T11:20:00')
  },
  { 
    id: 4, 
    codeFournisseur: 'TOY-WORLD',
    codeProduit: 'BBI-JOU-004', 
    nom: 'Jouet en peluche', 
    prix: { '30 cm': 15.99, '40 cm': 19.99 }, 
    devise: 'USD',
    region: 'Goma',
    classement: 'Jouets & Éveil',
    categorie: 'Jouet',
    quantiteTotal: { 'lin': 15, 'chocolat': 10, 'rose': 8 },
    type: 'Peluche',
    taille: ['30 cm', '40 cm'],
    couleur: ['lin','chocolat', 'rose'],
    description: 'Peluche douce en forme d\'ours pour câlins.', 
    imagesParCouleur: {
      'lin' : '/assets/imagesProduits/bbi-jou-004/lin.jpeg',
      'chocolat' : '/assets/imagesProduits/bbi-jou-004/chocolat.jpeg',
      'rose' : '/assets/imagesProduits/bbi-jou-004/rose.jpeg'
    },
    dateAjout: new Date('2024-02-01T08:00:00'),
    dateModification: new Date('2024-02-05T09:00:00')
  },
  { 
    id: 5, 
    codeFournisseur: 'KID-TOYS',
    codeProduit: 'BBI-JOU-005', 
    nom: 'Cube d’éveil', 
    prix: { '15 cm': 18.99, '20 cm': 22.50 }, 
    devise: 'USD',
    region: 'Beni',
    classement: 'Jouets & Éveil',
    categorie: 'Jouet',
    quantiteTotal: { 'bois': 5, 'rouge': 12, 'jaune': 10, 'bleu': 15 },
    type: 'Éveil',
    taille: ['15 cm', '20 cm'],
    couleur: ['bois','rouge', 'jaune', 'bleu'],
    description: 'Cube sensoriel avec couleurs, textures et sons.', 
    imagesParCouleur: {
      'bois' : '/assets/imagesProduits/bbi-jou-005/bois.jpeg',
      'rouge' : '/assets/imagesProduits/bbi-jou-005/rouge.jpeg',
      'jaune' : '/assets/imagesProduits/bbi-jou-005/jaune.jpeg',
      'bleu' : '/assets/imagesProduits/bbi-jou-005/bleu.jpeg',
    },
    dateAjout: new Date('2024-02-10T14:00:00'),
    dateModification: new Date('2024-02-10T14:00:00')
  },
  { 
    id: 6, 
    codeFournisseur: 'KID-TOYS',
    codeProduit: 'BBI-JOU-006', 
    nom: 'Hochet', 
    prix: { '10 cm': 7.99 }, 
    devise: 'USD',
    region: 'Butembo',
    classement: 'Jouets & Éveil',
    categorie: 'Jouet',
    quantiteTotal: { 'bisque': 20, 'vert': 15, 'bleu': 25, 'rose': 30 },
    type: 'Éveil',
    taille: ['10 cm'],
    couleur: ['bisque', 'vert', 'bleu', 'rose'],
    description: 'Hochet facile à tenir, sans BPA.', 
    imagesParCouleur: {
      'bisque' : '/assets/imagesProduits/bbi-jou-006/bisque.jpeg',
      'vert' : '/assets/imagesProduits/bbi-jou-006/vert.jpeg',
      'bleu' : '/assets/imagesProduits/bbi-jou-006/bleu.jpeg',
      'rose' : '/assets/imagesProduits/bbi-jou-006/rose.jpeg',
    },
    dateAjout: new Date('2024-02-12T11:00:00'),
    dateModification: new Date('2024-02-12T11:00:00')
  },
  { 
    id: 7, 
    codeFournisseur: 'MODA-KID',
    codeProduit: 'BBI-VET-007', 
    nom: 'T-shirt enfant', 
    prix: { '2 ans': 8.99 }, 
    devise: 'USD',
    region: 'Goma',
    classement: 'Vêtements & Mode',
    categorie: 'Vêtement',
    quantiteTotal: { 'noire': 40, 'rose': 55, 'jaune': 30, 'bleu': 20 },
    type: 'T-shirt',
    taille: ['2 ans'],
    couleur: ['noire', 'rose', 'jaune', 'bleu'],
    description: 'T-shirt coton avec motif dinosaure fun.', 
    imagesParCouleur: {
      'noire' : '/assets/imagesProduits/bbi-vet-007/noire.jpeg',
      'rose' : '/assets/imagesProduits/bbi-vet-007/rose.jpeg',
      'jaune' : '/assets/imagesProduits/bbi-vet-007/jaune.jpeg',
      'bleu' : '/assets/imagesProduits/bbi-vet-007/bleu.jpeg',
    },
    dateAjout: new Date('2024-03-01T09:00:00'),
    dateModification: new Date('2024-03-05T10:30:00')
  },
  { 
    id: 8, 
    codeFournisseur: 'MODA-KID',
    codeProduit: 'BBI-VET-008', 
    nom: 'Short bébé', 
    prix: { '6 mois': 6.99 }, 
    devise: 'USD',
    region: 'Beni',
    classement: 'Vêtements & Mode',
    categorie: 'Vêtement',
    quantiteTotal: { 'gris': 25, 'bleu ciel': 40, 'rouge': 15 },
    type: 'Short',
    taille: ['6 mois'],
    couleur: ['gris', 'bleu ciel', 'rouge'],
    description: 'Short léger en coton idéal pour l\'été.', 
    imagesParCouleur: {
      'gris' : '/assets/imagesProduits/bbi-vet-008/gris.jpeg',
      'bleu ciel' : '/assets/imagesProduits/bbi-vet-008/bleu-ciel.jpeg',
      'rouge' : '/assets/imagesProduits/bbi-vet-008/rouge.jpeg',
    },
    dateAjout: new Date('2024-03-02T15:00:00'),
    dateModification: new Date('2024-03-02T15:00:00')
  },
  { 
    id: 9, 
    codeFournisseur: 'PHARMA-BABY',
    codeProduit: 'BBI-ALI-009', 
    nom: 'Biberon', 
    prix: { '240 ml': 7.99, '350 ml': 10.50 }, 
    devise: 'USD',
    region: 'Butembo',
    classement: 'Repas & Alimentation',
    categorie: 'Alimentation',
    quantiteTotal: { 'transparent': 60, 'bleu': 30, 'rose': 30 },
    type: 'Biberon',
    taille: ['240 ml', '350 ml'],
    couleur: ['transparent', 'bleu', 'rose'],
    description: 'Biberon en plastique sans BPA, anti-colique.', 
    imagesParCouleur: {
      'transparent' : '/assets/imagesProduits/bbi-ali-009/transparent.jpeg',
      'bleu' : '/assets/imagesProduits/bbi-ali-009/bleu.jpeg',
      'rose' : '/assets/imagesProduits/bbi-ali-009/rose.jpeg',
    },
    dateAjout: new Date('2024-03-05T10:00:00'),
    dateModification: new Date('2024-03-10T16:00:00')
  },
  { 
    id: 10, 
    codeFournisseur: 'PHARMA-BABY',
    codeProduit: 'BBI-ALI-010', 
    nom: 'Tasse apprentissage', 
    prix: { '150 ml': 4.99 }, 
    devise: 'USD',
    region: 'Goma',
    classement: 'Repas & Alimentation',
    categorie: 'Alimentation',
    quantiteTotal: { 'rose': 40, 'bleu': 40, 'chocolat': 20 },
    type: 'Tasse',
    taille: ['150 ml'],
    couleur: ['rose', 'bleu', 'chocolat'],
    description: 'Tasse avec poignées pour apprendre à boire.', 
    imagesParCouleur: {
      'rose' : '/assets/imagesProduits/bbi-ali-010/rose.jpeg',
      'bleu' : '/assets/imagesProduits/bbi-ali-010/bleu.jpeg',
      'chocolat' : '/assets/imagesProduits/bbi-ali-010/chocolat.jpeg',
    },
    dateAjout: new Date('2024-03-06T11:00:00'),
    dateModification: new Date('2024-03-06T11:00:00')
  },
  { 
    id: 11, 
    codeFournisseur: 'TOY-WORLD',
    codeProduit: 'BBI-JOU-011', 
    nom: 'Jouet à empiler', 
    prix: { '20cm': 9.99 }, 
    devise: 'USD',
    region: 'Beni',
    classement: 'Jouets & Éveil',
    categorie: 'Jouet',
    quantiteTotal: { 'multicolore': 18, 'rose': 12 },
    type: 'Construction',
    taille: ['20cm'],
    couleur: ['multicolore', 'rose'],
    description: 'Anneaux colorés en plastique résistant à empiler.', 
    imagesParCouleur: {
      'multicolore' : '/assets/imagesProduits/bbi-jou-011/multicolore.jpeg',
      'rose' : '/assets/imagesProduits/bbi-jou-011/rose.jpeg',
    },
    dateAjout: new Date('2024-03-15T09:00:00'),
    dateModification: new Date('2024-03-15T09:00:00')
  },
  {
    id: 12, 
    codeFournisseur: 'WOOD-GAME',
    codeProduit: 'BBI-JOU-012', 
    nom: 'Puzzle en bois', 
    prix: { '20x20cm': 14.99 },
    devise: 'USD',
    region: 'Butembo',
    classement: 'Jouets & Éveil',
    categorie: 'Jouet',
    quantiteTotal: { 'bois': 10, 'bleu': 15, 'vert': 15 },
    type: 'Puzzle',
    taille: ['20x20cm'],
    couleur: ['bois', 'bleu', 'vert'],
    description: 'Puzzle éducatif en bois 12 pièces pour enfant.', 
    imagesParCouleur: {
      'bois' : '/assets/imagesProduits/bbi-jou-012/bois.jpeg',
      'bleu' : '/assets/imagesProduits/bbi-jou-012/bleu.jpeg',
      'vert' : '/assets/imagesProduits/bbi-jou-012/vert.jpeg',
    },
    dateAjout: new Date('2024-03-18T14:20:00'),
    dateModification: new Date('2024-03-20T10:00:00')
  },
  { 
    id: 13, 
    codeFournisseur: 'ACC-DIST',
    codeProduit: 'BBI-ACC-013', 
    nom: 'Casquette enfant', 
    prix: { '48 cm': 15000 }, 
    devise: 'CDF',
    region: 'Goma',
    classement: 'Vêtements & Mode',
    categorie: 'Accessoire',
    quantiteTotal: { 'rouge': 20, 'blanc': 15, 'vert': 10, 'noire': 25 },
    type: 'Chapeau',
    taille: ['48 cm'],
    couleur: ['rouge', 'blanc', 'vert', 'noire'],
    description: 'Casquette légère et colorée, protection UV.', 
    imagesParCouleur: {
      'rouge' : '/assets/imagesProduits/bbi-acc-013/rouge.jpeg',
      'blanc' : '/assets/imagesProduits/bbi-acc-013/blanc.jpeg',
      'vert' : '/assets/imagesProduits/bbi-acc-013/vert.jpeg',
      'noire' : '/assets/imagesProduits/bbi-acc-013/noire.jpeg',
    },
    dateAjout: new Date('2024-04-01T10:00:00'),
    dateModification: new Date('2024-04-01T10:00:00')
  },
  { 
    id: 14, 
    codeFournisseur: 'BBI',
    codeProduit: 'BBI-VET-014', 
    nom: 'Veste bébé', 
    prix: { '9-12 mois': 19.99 }, 
    devise: 'USD',
    region: 'Beni',
    classement: 'Vêtements & Mode',
    categorie: 'Vêtement',
    quantiteTotal: { 'bleu fonce': 8, 'blanc': 12, 'rose': 10 },
    type: 'Veste',
    taille: ['9-12 mois'],
    couleur: ['bleu fonce', 'blanc', 'rose'],
    description: 'Veste chaude en polaire, avec capuche.', 
    imagesParCouleur: {
      'bleu fonce' : '/assets/imagesProduits/bbi-vet-014/bleu-fonce.jpeg',
      'blanc' : '/assets/imagesProduits/bbi-vet-014/blanc.jpeg',
      'rose' : '/assets/imagesProduits/bbi-vet-014/rose.jpeg',
    },
    dateAjout: new Date('2024-04-05T08:30:00'),
    dateModification: new Date('2024-04-10T15:00:00')
  },
  { 
    id: 15, 
    codeFournisseur: 'WOOD-GAME',
    codeProduit: 'BBI-JOU-015', 
    nom: 'Jouet musical', 
    prix: { 'Taille unique': 16.99 }, 
    devise: 'USD',
    region: 'Butembo',
    classement: 'Jouets & Éveil',
    categorie: 'Jouet',
    quantiteTotal: { 'multicolor bois': 14, 'rose': 6 },
    type: 'Musical',
    taille: ['Taille unique'],
    couleur: ['multicolor bois', 'rose'],
    description: 'Petit xylophone en bois pour débuter la musique.', 
    imagesParCouleur: {
      'multicolor bois' : '/assets/imagesProduits/bbi-jou-015/multicolor.jpeg',
      'rose' : '/assets/imagesProduits/bbi-jou-015/rose.jpeg'
    },
    dateAjout: new Date('2024-04-12T13:00:00'),
    dateModification: new Date('2024-04-12T13:00:00')
  },
  { 
    id: 16, 
    codeFournisseur: 'TOY-WORLD',
    codeProduit: 'BBI-JOU-016', 
    nom: 'Doudou', 
    prix: { '25x25cm': 12.99 },
    devise: 'USD',
    region: 'Goma',
    classement: 'Jouets & Éveil',
    categorie: 'Jouet',
    quantiteTotal: { 'lin': 25, 'rose': 20, 'bleu': 15 },
    type: 'Doudou',
    taille: ['25x25cm'],
    couleur: ['lin','rose', 'bleu'],
    description: 'Doudou plat en forme de lapin, très doux.', 
    imagesParCouleur: {
      'lin' : '/assets/imagesProduits/bbi-jou-016/lin.jpeg',
      'rose' : '/assets/imagesProduits/bbi-jou-016/rose.jpeg',
      'bleu' : '/assets/imagesProduits/bbi-jou-016/bleu.jpeg'
    },
    dateAjout: new Date('2024-04-15T10:00:00'),
    dateModification: new Date('2024-04-15T10:00:00')
  },
  { 
    id: 17, 
    codeFournisseur: 'KID-TOYS',
    codeProduit: 'BBI-JOU-017', 
    nom: 'Balle sensorielle', 
    prix: { '10 cm': 8.99, '15 cm': 11.50 },
    devise: 'USD',
    region: 'Beni',
    classement: 'Jouets & Éveil',
    categorie: 'Jouet',
    quantiteTotal: { 'multicolor': 30, 'orange': 20, 'bleu': 25 },
    type: 'Éveil',
    taille: ['10 cm', '15 cm'],
    couleur: ['multicolor', 'orange' ,'bleu'],
    description: 'Balle colorée avec différentes textures pour la préhension.', 
    imagesParCouleur: {
      'multicolor' : '/assets/imagesProduits/bbi-jou-017/multicolor.jpeg',
      'orange' : '/assets/imagesProduits/bbi-jou-017/orange.jpeg',
      'bleu' : '/assets/imagesProduits/bbi-jou-017/bleu.jpeg'
    },
    dateAjout: new Date('2024-04-20T11:00:00'),
    dateModification: new Date('2024-04-22T09:30:00')
  },
  { 
    id: 18, 
    codeFournisseur: 'DECO-BABY',
    codeProduit: 'BBI-EQP-018', 
    nom: 'Tapis d’éveil', 
    prix: { '80x80cm': 24.99 },
    devise: 'USD',
    region: 'Butembo',
    classement: 'Chambre & Déco',
    categorie: 'Équipement',
    quantiteTotal: { 'motifs jungle': 10, 'rose': 5 },
    type: 'Tapis',
    taille: ['80x80cm'],
    couleur: ['motifs jungle', 'rose'],
    description: 'Tapis d\'éveil rembourré avec arches et jouets amovibles.', 
    imagesParCouleur: {
      'motifs jungle' : '/assets/imagesProduits/bbi-eqp-018/motifs-jungle.jpeg',
      'rose' : '/assets/imagesProduits/bbi-eqp-018/rose.jpeg'
    },
    dateAjout: new Date('2024-05-01T10:00:00'),
    dateModification: new Date('2024-05-01T10:00:00')
  }
];